export * from './main.module';
export * from './services/main.service';
export * from './services/menu.service';
export * from './interfaces/main.interface';
export * from './interfaces/menu.interface';
export * from './components/body/body.component';
export * from './components/main-page/main-page.component';
export * from './components/menu/menu.component';
export * from './components/page-content/page-content.component';
